import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packetPath = resolve(root, "spec/HKLanguageLabPacket-v1.7.md");
const outputPath = resolve(root, "src/public-contract.ts");
const packet = await readFile(packetPath, "utf8");
const lines = packet.split(/\r?\n/u);

let inSection5 = false;
let heading = "";
let inTsFence = false;
let skipFence = false;
let fenceStart = 0;
let block = [];
const blocks = [];

for (let index = 0; index < lines.length; index += 1) {
  const line = lines[index];
  if (line.startsWith("# §5 —")) inSection5 = true;
  if (inSection5 && /^# §6 —/u.test(line)) break;
  if (!inSection5) continue;

  if (/^#{2,6} /u.test(line)) heading = line;

  if (!inTsFence && line === "```ts") {
    inTsFence = true;
    // The convenience views are deferred, and §5.11.4 is an executable
    // illustration of a future renderer, not a public type declaration.
    skipFence = heading.startsWith("### 5.10.4 ")
      || heading.startsWith("### 5.11.4 ");
    fenceStart = index + 1;
    block = [];
    continue;
  }

  if (inTsFence && line === "```") {
    if (!skipFence) blocks.push({ heading, fenceStart, source: block.join("\n") });
    inTsFence = false;
    skipFence = false;
    block = [];
    continue;
  }

  if (inTsFence) block.push(line);
}

if (inTsFence) throw new Error(`Unclosed TypeScript fence at packet line ${fenceStart}`);
if (blocks.length !== 19) {
  throw new Error(`Expected 19 live v1 TypeScript fences in §5, found ${blocks.length}`);
}

const exported = blocks.map(({ heading: blockHeading, fenceStart: line, source }) => {
  const withExports = source
    .replace(/^(type|interface)\s+/gmu, "export $1 ")
    .replace(/^function\s+/gmu, "export declare function ");
  return `// ${blockHeading} — packet line ${line}\n${withExports}`;
});

const header = `/**
 * GENERATED FILE — do not hand-edit.
 * Hong Kong Cantonese Language Lab public contract 5.0.16.
 * Source authority: Implementation Packet v1.7, live v1 TypeScript fences in §5.
 * §5.10.4 convenience views are intentionally excluded: DEFERRED / NON-v1.
 * §5.11.4 executable illustration is excluded: no renderer implementation.
 * Generated by scripts/generate-types.mjs.
 */`;

await writeFile(outputPath, `${header}\n\n${exported.join("\n\n")}\n`, "utf8");
