/**
 * GENERATED FILE — do not hand-edit.
 * Hong Kong Cantonese Language Lab public contract 5.0.14.
 * Source authority: Implementation Packet v1.5, live v1 TypeScript fences in §5.
 * §5.10.4 convenience views are intentionally excluded: DEFERRED / NON-v1.
 * Generated by scripts/generate-types.mjs.
 */

// ## 5.2 Core conventions — packet line 2570
export type JsonValue =
  | null | boolean | number | string
  | JsonValue[]
  | { [key: string]: JsonValue };

export type TokenType =
  | "han" | "latin" | "digit" | "punct_cjk" | "punct_latin"
  | "space" | "symbol" | "emoji" | "script_other" | "unknown";

export type EntityType =
  | "person" | "person.surname" | "person.foreign"
  | "place.region" | "place.district" | "place.area" | "place.village"
  | "place.topographic" | "street" | "building" | "facility"
  | "org.company" | "org.institution" | "org.government"
  | "work" | "event" | "other";

// ## 5.3 Version record — packet line 2616
export interface Versions {
  schemaVersion: string;      // "1.0" — document shape
  contractVersion: string;    // current producer emits "5.0.14" (CHG-032/035/036/037/038/039/040/041/042/044/045/046/047/048)
  providerSnapshotId: string | null;   // CHG-037 A — id of the PINNED snapshot, or null =
                                       // no pinned provider snapshot was used. One meaning each.
  engineVersion: string;      // semver of @hklang/engine
  lexiconVersion: string;     // packaged linguistic data
  rulesVersion: string;       // romanisation convention tables + generator rules
  segmenterVersion: string;   // identifies the segmenter implementation AND its model/lexicon
  userDataVersion: number;    // exact integer 0..9007199254740991; starts at 0; one global increment per committed mutation
}

// ## 5.4 The Analysis document — packet line 2642
export interface Analysis {
  schemaVersion: string;
  offsetUnit: "utf16";
  source: string;                  // verbatim; INV-1
  sourceHash: string;              // stable hash, for cache and directive binding
  versions: Versions;
  optionsHash: string;             // hash of the normalised options actually used
  documentContextUsed: boolean;    // CHG-029

  tokens: Token[];                 // strict partition of source (INV-2)
  entities: Entity[];              // overlay; nested allowed, no partial overlap (INV-16)
  regions: AmbiguousRegion[];      // boundary-ambiguous regions (RULE-ENT-6)
  termResolutions: TermResolution[]; // core L4 selected/conflict states (CHG-044 H)

  diagnostics: Diagnostic[];        // analysis/content diagnostics from this processText call only
  debug?: DebugPayload;            // present only when requested (§5.16)
  ext?: { [key: string]: JsonValue }; // serialisable extension namespace (§5.17)
}

export interface AmbiguousRegion {
  id: string;
  span: [number, number];
  kind: "entity_boundary";
  alternatives: EntityBoundaryCandidate[]; // at least two; source-bound
  ranked: boolean;                         // false for comparable candidates
}

export interface EntityBoundaryCandidate {
  span: [number, number];
  text: string;                            // exact source slice
  type: EntityType;
  detectionEvidence: DetectionEvidence[];
  confidence: Confidence;
}

// ## 5.5 The value envelope — packet line 2689
export interface Value<T> {
  value: T | null;
  status: Status;
  provenance: Provenance;
  confidence: Confidence;
  evidenceClass: EvidenceClass | null;   // E1a|E1b|E1c|E2|E3|E4|E5|E6|E7
  externalAttestation: ExternalAttestation;   // tri-state — CHG-032 item 6
  attestation?: Attestation | null;
  scopeDowngrade?: "class_applied_to_individual";
  alternatives: Candidate<T>[];
  ranked: boolean;                       // are alternatives ordered by a prior?
  cautions: CautionCode[];
  reason?: ReasonCode;                   // why unresolved/unsupported
  derivedFrom?: DerivedFrom;             // cross-layer consumption (§5.7.3)
  inheritedFrom?: InheritanceRef;        // per selected channel; CHG-044 K
}

export type ExternalAttestation =
  | "attested"        // someone outside the user's own material demonstrably uses this
  | "not_attested"    // the question is meaningful here, and the answer is no
  | "not_applicable"; // the question is meaningless for this layer — e.g. an L2 reading

export interface Attestation {
  scope: "individual"|"institution"|"place_instance"|"class";
  sourceRef: string; asOf: string;
}

// CHG-032 item 4: when status is ambiguous or conflict, `value` is null, so the
// candidates are where ALL the evidence lives. The Lab must be able to answer
// "why is candidate A here, and why is candidate B here?" from this object alone.
export interface CandidateBase<T> {
  value: T;
  rank?: number;                         // present iff the parent has ranked === true
  evidenceClass: EvidenceClass | null;
  externalAttestation: ExternalAttestation;
  attestation?: Attestation | null;
  scopeDowngrade?: "class_applied_to_individual";
  support?: Confidence;                  // candidate-level support; NOT the parent's confidence
  attestationCount?: number;             // where counts exist (§2.7 induction)
  cautions: CautionCode[];
  variation?: VariationKind;             // L2 only: lexical|register|sociophonetic|sandhi|uncertain
  note?: string;
}

export type Candidate<T> = InheritedCandidate<T> | NonInheritedCandidate<T>;

export interface InheritedCandidate<T> extends CandidateBase<T> {
  provenance: "inherited";
  inheritedFrom: InheritanceRef;
}

export interface NonInheritedCandidate<T> extends CandidateBase<T> {
  provenance: Exclude<Provenance, "inherited">;
  inheritedFrom?: never;
}

// ### 5.5.2 Closed vocabularies — packet line 2778
export type Status      = "resolved"|"fallback"|"ambiguous"|"conflict"|"unresolved"|"unsupported"|"out_of_scope";
export type Provenance  = "user_glossary"|"entity_record"|"convention_table"|"lexicon"
                 | "rule_engine"|"external"|"inherited"|"none";
export type Confidence  = "high"|"medium"|"low"|"none";
export type EvidenceClass = "E1a"|"E1b"|"E1c"|"E2"|"E3"|"E4"|"E5"|"E6"|"E7";
export type StoreEvidenceClass = "E1a"|"E1b"|"E1c"|"E2";                                  // CHG-044 C1
export type FormKind    = "romanisation"|"official_name"|"native_original"|"translation"|"hybrid";  // CHG-027
export type VariationKind = "lexical"|"register"|"sociophonetic"|"sandhi"|"uncertain";

export type ReasonCode =
  | "reading_not_found"
  | "number_reading_requires_context"
  | "lexicon_unavailable"
  | "unsupported_code_point"
  | "malformed_input"
  | "no_known_english_form";

export type CautionCode =
  | "stale_source"
  | "overrides_official"
  | "decomposed_not_attested"
  | "source_unavailable"
  | "non_hk_convention_suspected"
  | "cjk_non_chinese_suspected"
  | "foreign_origin_suspected"
  | "sibilant_class_unknown"
  | "multiple_conventions"
  | "spelling_collision"
  | "bearer_spelling_unknown"
  | "non_chinese_script"
  | "window_ceiling_reached"
  | "official_name_expected";

// ## 5.6 Tokens, readings and romanisation units — packet line 2834
export interface Token {
  id: string;
  span: [number, number];
  text: string;                        // verbatim slice
  type: TokenType;                     // §3.3
  segment?: { matched: string; source: "lexicon"|"user_glossary"|"character"|"forced" };
  reading: Value<Reading>;             // L2
  romanisation: Value<Romanisation>;   // L3R — available on ANY Cantonese-readable token
  keyTransform?: { from: string; to: string; kind: "variant_fold"|"simplified_fold"|"nfc" };
}

export interface Reading {
  jyutping: string;                    // canonical serialisation
  syllables: Syllable[];
  alignmentGroups: GroupedAlignment[]; // [] when no grouped alignment exists
}
export interface Syllable {
  span: [number, number] | null;       // null only when align === "grouped"
  jyutping: string;
  initial: string;                     // "" for zero-initial
  final: string;
  tone: 1|2|3|4|5|6;
  syllabic: boolean;
  align: "exact"|"spread"|"grouped";   // "unaligned" is forbidden (RULE-JP-3)
}

export interface GroupedAlignment {
  span: [number, number];              // one shared source span
  syllableIndices: [number, number, ...number[]]; // local indices; at least two
}

// CHG-032 item 1: discriminated union. v0.1 required BOTH a canonical `text` and a
// `units` array on every form, which is unsatisfiable: an assembled name has no
// canonical text until a style is applied, and a verbatim form such as "Kowloon" or
// "Fanling" has no meaningful syllable-by-syllable decomposition.
export type Romanisation = VerbatimRomanisation | AssembledRomanisation;

export interface VerbatimRomanisation {
  formKind: "romanisation";
  assembled: false;
  text: string;                        // exact supplied/attested spelling — casing and
                                       // punctuation preserved; part of the attested fact
  units?: never;
  grouping?: never;
}

export interface AssembledRomanisation {
  formKind: "romanisation";
  assembled: true;
  units: RomanisationUnit[];           // caseless
  grouping: number[][];                // advisory word grouping of LOCAL unit indices; never authoritative
  text?: never;                        // there is no canonical rendering until
                                       // @hklang/style is given a profile. See RULE-API-10.
}

export interface RomanisationUnit {
  id: string;                          // opaque. DETERMINISTIC for an identical full input
                                       // tuple; NON-PERSISTENT across any change (RULE-API-13)
  span: [number, number];
  text: string;                        // CASELESS
  syllable: string;
  role?: "surname"|"given"|"prefix"|"specific"|"generic";
  provenance: Provenance;
  evidenceClass: EvidenceClass;
  externalAttestation: ExternalAttestation;
  scopeDowngrade?: "class_applied_to_individual";
  sibilantClass?: string;
}

// ## 5.7 Entities and English forms — packet line 2919
export interface Entity {
  id: string;
  span: [number, number];
  text: string;
  type: EntityType;                    // §4.2, dotted; consumers may prefix-match
  primary: boolean;                    // exactly one primary per position (INV-16)
  containedBy?: string;                // parent entity id when nested
  englishFallbackPolicy: "romanisation_allowed"|"prefer_original_recovery"|"no_automatic_romanisation";

  structure?: PersonNameStructure;     // person entities only
  detectionEvidence: DetectionEvidence[];
  detectionConfidence: Confidence;

  reading: Value<Reading>;             // L2, entity-conditioned (RULE-ENT-2)
  romanisation: Value<Romanisation>;   // L3R  ← DEC-…-001 container, part 1
  englishForm: Value<EnglishForm>;     // L3E  ← DEC-…-001 container, part 2
}

// Verbatim vs assembled remains discriminated on `assembled`. CHG-044 B closes
// the assembled branch without weakening the verbatim RC-4 boundary.
export type EnglishForm = VerbatimEnglishForm | AssembledEnglishForm;

export interface VerbatimEnglishForm {
  formKind: FormKind;                  // any of the five
  assembled: false;
  text: string;                        // exact; style can never alter it (RULE-API-6)
  person?: never;
  units?: never;
  grouping?: never;
  styleApplicable?: never;
}

export type AssembledEnglishForm =
  | StyledPersonEnglishForm
  | UnstyledPersonEnglishForm
  | NonPersonEnglishForm;

export interface AssembledEnglishFormBase {
  formKind: "romanisation" | "hybrid"; // the complete legal v1 assembled set
  assembled: true;
  units: EnglishAssemblyUnit[];
  grouping: number[][];                 // local indices into this form's units
  text?: never;
  // deliberately NO `styleVariants`
}

export interface StyledPersonEnglishForm extends AssembledEnglishFormBase {
  person: true;
  styleApplicable: { scope: "givenName"; unitIds: string[] };
}

export interface UnstyledPersonEnglishForm extends AssembledEnglishFormBase {
  person: true;
  styleApplicable?: never;
}

export interface NonPersonEnglishForm extends AssembledEnglishFormBase {
  person: false;
  styleApplicable?: never;
}

export type EnglishAssemblyUnit =
  | RomanisedEnglishUnit
  | LiteralEnglishUnit
  | TranslatedEnglishUnit;

export type EnglishAssemblyRole =
  | "surname" | "given" | "western_given" | "prefix" | "specific" | "generic";
export type CantoneseEnglishAssemblyRole = Exclude<EnglishAssemblyRole, "western_given">;

export interface EnglishAssemblyUnitBase {
  id: string;                          // Analysis-local, deterministic (RULE-API-13)
  span: [number, number];              // source component represented by this unit
  text: string;
  role?: EnglishAssemblyRole;
  provenance: Provenance;
  evidenceClass: EvidenceClass | null;
  externalAttestation: ExternalAttestation;
  scopeDowngrade?: "class_applied_to_individual";
}

export interface RomanisedEnglishUnit extends EnglishAssemblyUnitBase {
  kind: "romanised";
  role?: CantoneseEnglishAssemblyRole;
  text: string;                        // caseless generated/conventional romanised unit
  syllable: string;                    // only this branch carries Cantonese syllable semantics
  generated: boolean;                 // true only when this unit was generated by the engine
  sibilantClass?: string;
}

export interface LiteralEnglishUnit extends EnglishAssemblyUnitBase {
  kind: "literal";
  text: string;                        // exact already-English source component
  syllable?: never;
  generated?: never;
  sibilantClass?: never;
}

export interface TranslatedEnglishUnit extends EnglishAssemblyUnitBase {
  kind: "translated";
  role?: CantoneseEnglishAssemblyRole;
  text: string;                        // exact translated/generic component, e.g. "Road"
  syllable?: never;
  generated?: never;
  sibilantClass?: never;
}

export interface DetectionEvidence {
  mechanism: "D1"|"D2"|"D3"|"D4"|"D5"|"D6"|"D7";
  span?: [number, number];             // e.g. the title 先生, which is OUTSIDE the entity span
  detail?: string;
}

// ### 5.7.2 Person name structure — packet line 3053
export interface PersonNameStructure {
  surname?: { span: [number, number]; compound: boolean };
  givenName?: { span: [number, number] };
  prefix?: { span: [number, number] };          // 阿 — romanised as a unit (Ah)
  westernGiven?: { span: [number, number] };    // already English; never romanised
  maidenSurname?: { span: [number, number] };
  order: "surname_first"|"given_first";
  parseAlternatives?: PersonNameStructure[];    // populated when 2+2 / 1+3 ambiguous (RULE-ENT-7)
}

// ### 5.7.3 Cross-layer derivation — packet line 3067
// CHG-044 E: the owner discriminant makes zero-owner and two-owner states impossible,
// and each branch admits only channels actually present on that owner.
export type AnnotationRef = EntityAnnotationRef | TokenAnnotationRef;

export interface EntityAnnotationRef {
  owner: "entity";
  entityId: string;
  tokenId?: never;
  channel: "reading" | "romanisation" | "englishForm";
}

export interface TokenAnnotationRef {
  owner: "token";
  entityId?: never;
  tokenId: string;
  channel: "reading" | "romanisation";
}

export type RomanisationRef = EntityRomanisationRef | TokenRomanisationRef;

export interface EntityRomanisationRef {
  owner: "entity";
  entityId: string;
  tokenId?: never;
  channel: "romanisation";
}

export interface TokenRomanisationRef {
  owner: "token";
  entityId?: never;
  tokenId: string;
  channel: "romanisation";
}

export interface DerivedFrom {
  layer: "L3R";
  romanisationRef: RomanisationRef;    // exact one owner, romanisation only, no parsing
  fallbackReason: "no_known_english_form";
  directStoreRead: false;              // CHG-025 — Chain B did not itself read the HKR store
}

// ### 5.7.4 `InheritanceRef` — typed, resolvable inheritance (CHG-039 A) — packet line 3118
export type InheritanceRef =
  | { kind: "analysis";        entityId: string; contextId?: never; ref?: never }
                                                    // an antecedent mention in THIS Analysis
  | { kind: "documentContext"; contextId: string; ref: string; entityId?: never };
                                                    // an entry in the DocumentContext INPUT

// ## 5.8 Term directives (L4) — packet line 3136
export interface TermResolution {
  span: [number, number];
  sourceText: string;
  entryScope: "lexical" | "phrase";
  result: Value<TermRendering>;
}

export interface TermRendering {
  preferred: string;                   // exact stored value
  entryId: string;                     // source StoreEntry id
  entryScope: "lexical" | "phrase";
  note?: string;
}

export interface TermDirective {
  span: [number, number];
  sourceText: string;
  preferred: string;                   // the user's stipulated English rendering
  entryScope: "lexical"|"phrase";
  entryId: string;
  evidenceClass: StoreEvidenceClass;
  note?: string;
}

// ## 5.9 Store contract — packet line 3170
export type StoreName = "pronunciation" | "translation" | "hk_romanisation";
export type StoreEntryScope = "lexical" | "phrase" | "entity";
export type StoreMatch = "exact" | "contextual";

export interface StoreMatchContext {
  precededBy?: string[];
  followedBy?: string[];
  entityType?: EntityType;
  documentTag?: string;                         // exact membership in current ProcessOptions.documentTags
}

export interface StoreEntryBase {
  id: string;
  key: string;
  value: string;
  caseSensitive: boolean;                      // persisted; creation default false (CHG-044 I)
  match: StoreMatch;
  context?: StoreMatchContext;
  note?: string;
  verifiedAt?: string | null;                  // property of the RECORD (DEC-…-008)
  createdAt: string; updatedAt: string; revision: number;
}

export type StoreScopeFields =
  | { entryScope: "entity"; entityTypeHint?: EntityType }
  | { entryScope: "lexical" | "phrase"; entityTypeHint?: never };

export type ApplicableStoreEvidence =
  | { evidenceClass: "E1a" | "E1b"; externalAttestation: "not_attested";
      attestation: null }
  | { evidenceClass: "E1c"; externalAttestation: "attested";
      attestation?: Attestation | null }
  | { evidenceClass: "E2"; externalAttestation: "attested";
      attestation: Attestation };

export type InapplicableStoreEvidence =
  | { evidenceClass: "E1a" | "E1b"; externalAttestation: "not_applicable";
      attestation: null }
  | { evidenceClass: "E1c"; externalAttestation: "not_applicable";
      attestation?: Attestation | null }
  | { evidenceClass: "E2"; externalAttestation: "not_applicable";
      attestation: Attestation };

export interface ValidStoreState {
  enabled: boolean;
  validation: { ok: true; errors: [] };
}

export type ValidStoreEntry = StoreEntryBase & ValidStoreState & (
  | (StoreScopeFields & { store: "pronunciation"; formKind?: never }
     & InapplicableStoreEvidence)
  | (StoreScopeFields & { store: "hk_romanisation"; formKind?: never }
     & ApplicableStoreEvidence)
  | ({ store: "translation"; entryScope: "entity"; entityTypeHint?: EntityType;
       formKind: FormKind } & ApplicableStoreEvidence)
  | ({ store: "translation"; entryScope: "lexical" | "phrase";
       entityTypeHint?: never; formKind?: never } & InapplicableStoreEvidence)
);

// A draft with a legal user evidence class can still fail cross-field validation
// (for example E2 without Attestation). It is quarantined explicitly, never enabled.
export interface InvalidStoreEntry extends StoreEntryBase {
  store: StoreName;
  entryScope: StoreEntryScope;
  entityTypeHint?: EntityType;
  formKind?: FormKind;
  enabled: false;
  evidenceClass: StoreEvidenceClass;
  externalAttestation: ExternalAttestation;
  attestation?: Attestation | null;
  validation: { ok: false; errors: [ValidationError, ...ValidationError[]] };
}

export type StoreEntry = ValidStoreEntry | InvalidStoreEntry;

export interface ValidationError {
  code: string;                               // stable machine code; consumers preserve unknown codes
  path: (string | number)[];                  // path inside the submitted draft/import row
  message: string;
}

export interface StoreListQuery {
  enabled?: boolean;
  entryScope?: StoreEntryScope;
  evidenceClass?: StoreEvidenceClass;
}

export interface StoreSearchOptions extends StoreListQuery {
  context?: StoreMatchContext;
}

export interface StoreEntryDraft {
  key: string;
  value: string;
  entryScope?: StoreEntryScope;               // default "lexical"
  entityTypeHint?: EntityType;
  formKind?: FormKind;
  caseSensitive?: boolean;                    // default false
  match?: StoreMatch;                         // default "exact"
  context?: StoreMatchContext;
  enabled?: boolean;                          // default true unless validation fails
  evidenceClass?: StoreEvidenceClass;         // default "E1a"
  externalAttestation?: ExternalAttestation;  // validated/normalised by RULE-API-12
  attestation?: Attestation | null;
  note?: string;
  verifiedAt?: string | null;
}

export type StoreEntryPatch = Partial<StoreEntryDraft>;

export interface StoreCreateResult {
  entry: StoreEntry;
  conflicts: StoreEntry[];
}

export interface StoreExport {
  schemaVersion: "1.0";
  store: StoreName;
  exportedAt: string;
  engineVersion: string;
  entries: StoreEntry[];
}

export type StoreImportData = JsonValue;
export type StoreImportMode = "preview" | "apply";
export type StoreImportAction = "add" | "update" | "conflict" | "invalid";

export interface StoreImportRow {
  index: number;
  action: StoreImportAction;
  input: JsonValue;                            // exact submitted row for audit
  entry?: StoreEntry;                         // absent when structurally invalid
  conflicts: StoreEntry[];
  errors: ValidationError[];
}

export interface ImportPreview {
  mode: "preview";
  store: StoreName;
  writesApplied: false;
  rows: StoreImportRow[];
}

export interface ImportResult {
  mode: "apply";
  store: StoreName;
  writesApplied: boolean;                       // true iff at least one row was written
  rows: StoreImportRow[];
  userDataVersion: number;                      // exact integer 0..9007199254740991 after this transaction
}

export interface StoreApi {
  list(store: StoreName, query?: StoreListQuery): StoreEntry[];
  get(store: StoreName, id: string): StoreEntry | null;
  create(store: StoreName, draft: StoreEntryDraft): StoreCreateResult;
  update(store: StoreName, id: string, patch: StoreEntryPatch): StoreEntry;
  remove(store: StoreName, id: string): void;
  setEnabled(store: StoreName, id: string, enabled: boolean): StoreEntry;
  search(store: StoreName, text: string, opts?: StoreSearchOptions): StoreEntry[];
  exportJson(store: StoreName): StoreExport;    // canonical, full fidelity
  exportCsv(store: StoreName): string;          // lossy; header declares omitted fields
  importJson(store: StoreName, data: StoreImportData,
             mode: "preview"): ImportPreview;
  importJson(store: StoreName, data: StoreImportData,
             mode: "apply"): ImportResult;
  version(): number;                            // exact public userDataVersion domain; global across all stores
}

// ## 5.10 Public API — packet line 3382
export type EngineCreationResult =
  | EngineCreationSuccess
  | EngineCreationFailure;

export interface EngineCreationSuccess {
  ok: true;
  engine: Engine;
  diagnostics: Diagnostic[];
}

export interface EngineCreationFailure {
  ok: false;
  engine: null;
  diagnostics: [Diagnostic, ...Diagnostic[]];
}

export declare function createEngine(config: EngineConfig): EngineCreationResult;

export interface Engine {
  processText(input: string, options?: ProcessOptions): Analysis;
  versions(): Versions;
  stores: StoreApi;
  validateJyutping(s: string): JyutpingValidationResult;
}

export interface JyutpingValidationResult {
  ok: boolean;
  errors: string[];
}

export interface DebugOptions {
  lattice?: boolean;
  trace?: boolean;
}

export interface ProcessOptions {
  documentContext?: DocumentContext;   // OPTIONAL, v1 (CHG-029)
  documentTags?: string[];             // default []; opaque Store-matching labels (CHG-045 C)
  latinReadingPolicy?: "none"|"letter_names"|"loanword_lexicon";   // default "none"
  numberReadingPolicy?: "none"|"digits"|"cardinal";                // default "none"
  phoneticComponentHeuristic?: boolean;                            // default false
  debug?: DebugOptions;                                           // default off
  // NOTE (CHG-032 item 3): protectionConfidenceFloor is NOT here. Protection exists
  // only in the directive projection, so the floor lives in DirectiveSettings.
}

export interface DocumentContext {
  contextFormatVersion: "1";           // scheme version; see §5.10.2.1's ordered preimage
  id: string;                          // consumer-supplied document identity
  entities: EntityMemoryEntry[];       // carried forward from earlier chunks
}

// ### 5.10.2 `EntityMemoryEntry` — the cross-call wire contract (CHG-039 A) — packet line 3465
export interface EntityMemoryEntry {
  ref: string;                         // CONTEXT-LOCAL identity, unique within THIS
                                       // DocumentContext only (RULE-API-18).
  text: string;                        // the entity's source characters — the semantic anchor
  aliases?: string[];                  // explicitly enumerated, structurally justified (§5.10.2.2)
  type: EntityType;
  name?: MemoryPersonName;             // person entities only

  reading?:      MemoryChannel<MemoryReading>;
  romanisation?: MemoryChannel<MemoryRomanisation>;
  englishForm?:  MemoryChannel<MemoryEnglishForm>;
}

// A channel is PRESENT only when a value was actually selected. Its legal statuses are
// therefore exactly those §5.5.1 permits with a non-null value (CHG-040 A).
export interface MemoryChannel<T> {
  value: T;                                     // never null — absence is the absent field
  status: "resolved" | "fallback";              // NOT the full Status union
  provenance: Provenance;
  confidence: Confidence;
  evidenceClass: EvidenceClass | null;
  externalAttestation: ExternalAttestation;
  attestation?: Attestation | null;             // required where the source value had one
  scopeDowngrade?: "class_applied_to_individual";
  cautions: CautionCode[];
}

export interface MemoryPersonName {                    // no spans — component TEXT instead
  surnameText?: string;
  givenNameText?: string;
  prefixText?: string;                          // 阿
  westernGivenText?: string;
  maidenSurnameText?: string;
  compoundSurname: boolean;
  order: "surname_first" | "given_first";
}

export interface MemoryReading {                       // phonology only; no source alignment
  jyutping: string;
  syllables: ReadonlyArray<{
    jyutping: string; initial: string; final: string;
    tone: 1|2|3|4|5|6; syllabic: boolean;       // no `span`, no `align`
  }>;
}

export type MemoryRomanisation =
  | { formKind: "romanisation"; assembled: false; text: string;
      units?: never; grouping?: never }
  | { formKind: "romanisation"; assembled: true;  units: ReadonlyArray<MemoryUnit>;
      grouping: ReadonlyArray<ReadonlyArray<number>>; text?: never };
                                                    // indices into `units`, not ids

export type MemoryEnglishForm =
  | { formKind: FormKind; assembled: false; text: string; person?: never;
      units?: never; grouping?: never; styleApplicable?: never }
  | MemoryStyledPersonEnglishForm
  | MemoryUnstyledPersonEnglishForm
  | MemoryNonPersonEnglishForm;

export interface MemoryAssembledEnglishFormBase {
  formKind: "romanisation" | "hybrid";
  assembled: true;
  units: ReadonlyArray<MemoryEnglishAssemblyUnit>;
  grouping: ReadonlyArray<ReadonlyArray<number>>; // local indices into this form's units
  text?: never;
}

export interface MemoryStyledPersonEnglishForm extends MemoryAssembledEnglishFormBase {
  person: true;
  styleApplicable: { scope: "givenName"; unitIndices: ReadonlyArray<number> }; // local unit indices
}                                               // local indices only; never Analysis unit ids

export interface MemoryUnstyledPersonEnglishForm extends MemoryAssembledEnglishFormBase {
  person: true;
  styleApplicable?: never;
}

export interface MemoryNonPersonEnglishForm extends MemoryAssembledEnglishFormBase {
  person: false;
  styleApplicable?: never;
}

export interface MemoryUnit {                          // no `id`, no `span`
  text: string; syllable: string;
  role?: "surname"|"given"|"prefix"|"specific"|"generic";
  provenance: Provenance; evidenceClass: EvidenceClass;
  externalAttestation: ExternalAttestation;
  scopeDowngrade?: "class_applied_to_individual";
}

export type MemoryEnglishAssemblyUnit =
  | MemoryRomanisedEnglishUnit
  | MemoryLiteralEnglishUnit
  | MemoryTranslatedEnglishUnit;

export interface MemoryEnglishAssemblyUnitBase {       // no `id`, no `span`
  text: string;
  role?: EnglishAssemblyRole;
  provenance: Provenance;
  evidenceClass: EvidenceClass | null;
  externalAttestation: ExternalAttestation;
  scopeDowngrade?: "class_applied_to_individual";
}

export interface MemoryRomanisedEnglishUnit extends MemoryEnglishAssemblyUnitBase {
  kind: "romanised";
  role?: CantoneseEnglishAssemblyRole;
  syllable: string;
  generated: boolean;
  sibilantClass?: string;
}

export interface MemoryLiteralEnglishUnit extends MemoryEnglishAssemblyUnitBase {
  kind: "literal";
  syllable?: never;
  generated?: never;
  sibilantClass?: never;
}

export interface MemoryTranslatedEnglishUnit extends MemoryEnglishAssemblyUnitBase {
  kind: "translated";
  role?: CantoneseEnglishAssemblyRole;
  syllable?: never;
  generated?: never;
  sibilantClass?: never;
}

// ## 5.11 The style module — DEC-LANG-20260828-016 SETTLED — packet line 3711
// The Lab's full presentation range (§9.10). Used only by the generic render helpers.
export type StyleProfile = "hyphenated"|"joined"|"spaced"|"hyphen_title"|"surname_caps";

// CHG-042 D — the RC-3 toggle is narrower than StyleProfile and must stay narrower.
// The Reader's setting governs GIVEN-NAME JOINING of an assembled personal name and
// nothing else; `spaced`, `surname_caps` and `hyphen_title` are Lab presentation
// profiles and must not become Reader settings.
export type GeneratedPersonNameStyle = "hyphenated" | "joined";

// The complete general-L3R casing range already named by §2.2.4.
export type CasingProfile = "lower" | "sentence" | "title" | "upper";

export type AnnotationChannel = "reading" | "romanisation" | "englishForm";

export interface DisplayOptions {
  channels: ReadonlyArray<AnnotationChannel>;
  romanisationCasing?: CasingProfile;
  personNameStyle?: StyleProfile;
  includeAlternatives?: boolean;
}

export interface AnnotationProjection {
  schemaVersion: string;
  sourceHash: string;
  offsetUnit: "utf16";
  annotations: ProjectedAnnotation[];
}

export interface ProjectedAnnotation {
  ref: AnnotationRef;
  span: [number, number];
  sourceText: string;
  rendered: string | null;             // null when no selected/renderable value exists
  status: Status;
  confidence: Confidence;
  alternatives: string[];              // [] unless explicitly requested
  cautions: CautionCode[];
}

export interface RenderedVariant {
  profile: StyleProfile;
  text: string;
}

// All pure: same inputs ⇒ same output. No I/O, no store reads, no engine state.
export declare function renderPersonName(form: EnglishForm, profile: StyleProfile): string;
export declare function renderRomanisation(r: Romanisation, casing: CasingProfile): string;
export declare function renderVariants(form: EnglishForm, profiles: StyleProfile[]):
         RenderedVariant[];                           // the Lab's side-by-side view
export declare function projectAnnotations(a: Analysis, display: DisplayOptions): AnnotationProjection;
export declare function projectTranslationDirectives(a: Analysis, s: DirectiveSettings): TranslationDirectives;

// ## 5.12 Translation directives projection — packet line 3777
export interface DirectiveSettings {
  generatedPersonNameStyle: GeneratedPersonNameStyle;   // narrowed — CHG-042 D
  protectionConfidenceFloor?: Confidence;      // default "medium" — CHG-032 item 3
}

export interface TranslationDirectives {
  schemaVersion: string;
  sourceHash: string;                          // binds these directives to one exact source
  offsetUnit: "utf16";
  styleUsed: GeneratedPersonNameStyle;
  protectedSpans: ProtectedSpan[];             // non-overlapping, sorted (INV-17)
  termDirectives: TermDirective[];             // selected L4 guidance only; no conflicts
  unresolvedSemanticSpans: UnresolvedSemanticSpan[];
  diagnostics: Diagnostic[];                   // this projection invocation only; deterministic; [] when none
}

export type UnresolvedSemanticSpan =
  | { span: [number, number]; status: "ambiguous" | "conflict"; reason?: never }
  | { span: [number, number]; status: "unresolved" | "unsupported"; reason: ReasonCode };

export interface ProtectedSpan {
  span: [number, number];
  entityId: string;
  entityType: EntityType;
  replacement: string;                         // concrete; style already applied if applicable
  formKind: FormKind;
  assembled: boolean;
  provenance: Provenance;
  evidenceClass: EvidenceClass;
  externalAttestation: ExternalAttestation;
  protection: "strict"|"preferred"|"fallback";
  styleApplied: GeneratedPersonNameStyle | null;   // non-null only for licensed person units
  rationale: string;
}

// ## 5.13 Replaceable interfaces — packet line 3836
export interface ForcedTerm {
  span: [number, number];                     // inside `window`, UTF-16 source offsets
  text: string;                               // exact source slice
  entryId: string;                            // StoreEntry that forced the segment
}

export interface Lattice {
  window: [number, number];                   // source-bound analysis window
  edges: ReadonlyArray<LatticeEdge>;          // deterministic ascending edge.index
  alternatives: ReadonlyArray<LatticeAlternative>;
}

export interface LatticeEdgeBase {
  index: number;                              // local to this Lattice; not a durable id
  span: [number, number];
  text: string;                               // exact source slice
  matchedKey?: string;
}

export type LatticeEdge = ReferenceLatticeEdge | StoreLatticeEdge;

export interface ReferenceLatticeEdge extends LatticeEdgeBase {
  source: "lexicon" | "character";
  entryId?: never;
}

export interface StoreLatticeEdge extends LatticeEdgeBase {
  source: "user_glossary" | "forced";
  entryId: string;                             // StoreEntry that licensed/forced the edge
}

export interface LatticeAlternative {
  edgeIndices: [number, ...number[]];         // one complete candidate path through window
}

export interface Segmenter {
  id: string;                                  // contributes to segmenterVersion
  segment(text: string, window: [number, number],
          lexicon: Lexicon, forced: ForcedTerm[]): Lattice;
}

export interface LexiconReading {
  jyutping: string;                           // canonical RULE-JP-2 spelling
  variation?: VariationKind;
  frequency: number | null;
  sourceRef: string;
}

export interface LexEntry {
  key: string;
  readings: ReadonlyArray<LexiconReading>;
}

export interface CharEntry {
  character: string;
  readings: ReadonlyArray<LexiconReading>;
}

export interface LexiconCoverage {
  writtenCantonese: boolean;
  hkscs: boolean;
  wordLevel: boolean;
  frequencies: boolean;
}

export interface Lexicon {
  lookupWord(key: string): LexEntry[];
  lookupChar(cp: string): CharEntry[];
  frequency(key: string): number | null;       // required by RULE-JP-7's dominance threshold
  coverage(): LexiconCoverage;
}

// CHG-037 A — the conformant core NEVER calls a provider. It consumes an already-
// materialised, content-addressed snapshot supplied through EngineConfig.
// CHG-039 B — `id` is the hash of the SNAPSHOT IDENTITY, not of `entries` alone.
export interface ProviderSnapshot {
  id: string;                                  // SHA-256 digest of the ordered tagged-array
                                               // preimage in RULE-API-20. There is no other preimage;
                                               // do NOT encode this object generically.
  snapshotFormatVersion: "1";                  // scheme version; see RULE-API-20's preimage
  providerId: string;
  providerConfigHash: string;                  // provider configuration
  createdAt: string;                           // NON-SEMANTIC — excluded from `id` (see below)
  entries: ReadonlyArray<ProviderSnapshotEntry>;
}

export interface ProviderSnapshotEntry {
  inputHash: string;                           // hex SHA-256 over the canonical input;
                                               // MUST be unique within a snapshot
  output: CanonicalValue;
}

// The value domain §5.15.2's canonical encoder accepts. Provider outputs must be
// expressible in it, so no implementation invents a second encoding.
export type CanonicalValue =
  | null | boolean | string
  | CanonicalInteger
  | ReadonlyArray<CanonicalValue>
  | CanonicalObject;

export type CanonicalInt64Decimal = string;           // grammar/range are normative immediately below

export interface CanonicalInteger {
  readonly __int: CanonicalInt64Decimal;       // exactly this one property
}

export type CanonicalObject =
  { readonly [key: string]: CanonicalValue }
  & { readonly __int?: never };                // reserved key makes the union disjoint

export interface EngineConfig {
  engineVersion: string;
  lexiconVersion: string;                      // composite fingerprint (§5.15.1)
  rulesVersion: string;                        // composite fingerprint (§5.15.1)
  segmenterVersion: string;                    // identifies Segmenter + model/lexicon
  keyFormatVersion: string;                    // canonical encoder version (§5.15.2)
  lexicon: Lexicon;
  segmenter: Segmenter;
  stores: StoreApi;
  providerSnapshot?: ProviderSnapshot;         // the ONLY provider input surface; atomically validated by createEngine
}

// A LIVE provider lives outside processText, in an optional async orchestration layer
// that materialises a ProviderSnapshot and then calls the synchronous core.
export interface ExternalProvider<I, O> {             // OPTIONAL, orchestration layer only
  id: string;
  deterministic: false;
  call(input: I): Promise<O>;
}

// ## 5.14 Errors, diagnostics, and the no-throw contract — packet line 4034
export type DiagnosticCode =
  | "LEXICON_MISSING_CAPABILITY"
  | "WINDOW_CEILING_REACHED"
  | "SOURCE_UNAVAILABLE"
  | "IMPORT_VALIDATION_FAILED"
  | "TERM_DIRECTIVE_DROPPED_OVERLAP"
  | "PROVIDER_SNAPSHOT_INVALID";

export interface Diagnostic {
  code: DiagnosticCode;                        // closed for current producers
  severity: "info"|"warning"|"error";
  span?: [number, number];
  message: string;                             // human-readable; NOT for machine dispatch
  data?: { [key: string]: JsonValue };
}

// ## 5.16 Debug payload — packet line 4199
export interface ResolutionTrace {
  target: ResolutionTraceTarget;
  layer: "L2" | "L3R" | "L3E" | "L4";
  chain: string;                               // stable chain id, e.g. "B"
  steps: ResolutionTraceStep[];
}

export type ResolutionTraceTarget =
  | { kind: "annotation"; ref: AnnotationRef; index?: never }
  | { kind: "termResolution"; index: number; ref?: never }; // local index into Analysis.termResolutions

export interface ResolutionTraceStep {
  ordinal: number;
  source: string;                              // stable source/step id
  outcome: "hit" | "miss" | "not_applicable" | "conflict";
  entryIds?: string[];
  evidenceClass?: EvidenceClass;
  detail?: string;
}

export interface DebugPayload {
  lattice?: Lattice;                           // full segmentation lattice, opt-in
  trace?: ResolutionTrace[];                   // per-resolution-target trace: which steps ran, which fired
  segmentation: { inertAmbiguities: number; consequentialAmbiguities: number };
  rulePackAccuracy?: { syllableExactMatch: number; wholeNameExactMatch: number;
                       sibilantSubAccuracy: number; measuredAgainst: string };
}
